[platformio]
src_dir = main

[env:esp32-c3-recovery]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_upload.offset_address = 0x10000
extra_scripts = post:check_factory_size.py
build_flags =
  -DRADAR_FACTORY_BUILD=1
